// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcp4tMoNhEEv-GepWmVDz3s3zNWYFAxDo',
    appId: '1:557668953763:web:48f0509f5fe09e8234d916',
    messagingSenderId: '557668953763',
    projectId: 'tytanvpn-93208',
    authDomain: 'tytanvpn-93208.firebaseapp.com',
    storageBucket: 'tytanvpn-93208.firebasestorage.app',
    measurementId: 'G-JWLRR6HF51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzM5DsHdBoDh_eRYais7KiGWemR0gE7-Q',
    appId: '1:557668953763:android:94b834d5b61ea88834d916',
    messagingSenderId: '557668953763',
    projectId: 'tytanvpn-93208',
    storageBucket: 'tytanvpn-93208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqOcc4MDZbWcreM9tP947M7MwmXGXSDjI',
    appId: '1:557668953763:ios:0b5463af123707d834d916',
    messagingSenderId: '557668953763',
    projectId: 'tytanvpn-93208',
    storageBucket: 'tytanvpn-93208.firebasestorage.app',
    iosBundleId: 'com.example.tytan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqOcc4MDZbWcreM9tP947M7MwmXGXSDjI',
    appId: '1:557668953763:ios:0b5463af123707d834d916',
    messagingSenderId: '557668953763',
    projectId: 'tytanvpn-93208',
    storageBucket: 'tytanvpn-93208.firebasestorage.app',
    iosBundleId: 'com.example.tytan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcp4tMoNhEEv-GepWmVDz3s3zNWYFAxDo',
    appId: '1:557668953763:web:0b481cc787937fc134d916',
    messagingSenderId: '557668953763',
    projectId: 'tytanvpn-93208',
    authDomain: 'tytanvpn-93208.firebaseapp.com',
    storageBucket: 'tytanvpn-93208.firebasestorage.app',
    measurementId: 'G-QTZHGYR34T',
  );

}