// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArtfE12jXovLom7Q26yWh1ftFw_avtw7U',
    appId: '1:536467881479:web:85d46862125f603d8274a2',
    messagingSenderId: '536467881479',
    projectId: 'tytanvpn',
    authDomain: 'tytanvpn.firebaseapp.com',
    storageBucket: 'tytanvpn.firebasestorage.app',
    measurementId: 'G-M0890Y2PPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoW2Kpm7b0zdZtDM0X6IO4WJ6M06wa-Uw',
    appId: '1:536467881479:android:7f937dea7dc058788274a2',
    messagingSenderId: '536467881479',
    projectId: 'tytanvpn',
    storageBucket: 'tytanvpn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf946KCgeu9QZMDO-C8xW-nTs9ED4oL-w',
    appId: '1:536467881479:ios:777ca68a2f9f62a48274a2',
    messagingSenderId: '536467881479',
    projectId: 'tytanvpn',
    storageBucket: 'tytanvpn.firebasestorage.app',
    androidClientId: '536467881479-6oghu58f048v04dmevt6ltgqg8eqa950.apps.googleusercontent.com',
    iosClientId: '536467881479-20agv9tq9vv925mjco583bngku71q0is.apps.googleusercontent.com',
    iosBundleId: 'com.example.tytan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf946KCgeu9QZMDO-C8xW-nTs9ED4oL-w',
    appId: '1:536467881479:ios:777ca68a2f9f62a48274a2',
    messagingSenderId: '536467881479',
    projectId: 'tytanvpn',
    storageBucket: 'tytanvpn.firebasestorage.app',
    androidClientId: '536467881479-6oghu58f048v04dmevt6ltgqg8eqa950.apps.googleusercontent.com',
    iosClientId: '536467881479-20agv9tq9vv925mjco583bngku71q0is.apps.googleusercontent.com',
    iosBundleId: 'com.example.tytan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArtfE12jXovLom7Q26yWh1ftFw_avtw7U',
    appId: '1:536467881479:web:625f2dd55869b94a8274a2',
    messagingSenderId: '536467881479',
    projectId: 'tytanvpn',
    authDomain: 'tytanvpn.firebaseapp.com',
    storageBucket: 'tytanvpn.firebasestorage.app',
    measurementId: 'G-M0VTM2HTMN',
  );

}